### ISSUE TITLE
Can't run scala code with web application

### ISSUE THREAD

**Issue by jbuisine** [jbuisine/RO.PhotoAlbumProject#2]
Application uses child_process node package to run command line instructions.

When I want to throw a command to run scala, an error ocurred and says that source folder is not found. However, when I run command manually into my terminal, it works as excepted.

**Child process code :** spawn('scalac', ['-d', './../utilities/compile', '-cp', './../utilities/lib/json-simple-1.1.1.jar', './../src/*.scala']);
**Error:** source file './../src/*.scala' could not be found
**Command line which works :** scalac -d ./../utilities/compile -cp ./../utilities/lib/json-simple-1.1.1.jar ./../src/*.scala

Lines code involved :
- [Scala line code](https://github.com/jbuisine/RO.PhotoAlbumProject/blob/master/www/modules/routes/index.js#L49)
- [html code to decomment](https://github.com/jbuisine/RO.PhotoAlbumProject/blob/master/www/views/partials/nav.ejs#L54)

**Comment by geoffreyp** [comment]
The PR #4 fix the problem ;)

**Comment by jbuisine** [comment]
Thanks a lot ! :+1:
